### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by mb-wali** [cyverse-austria/condor#3]
* rename this repo to `ansible-condor`.
* find a way to specify the condor version. it can be the latest release
* this playbook should run for debian12 (bookworm)
* find which ports are used to communicate with workers and submit and vice-versa. please document these.
* Please document - the workflow as you described on the call - and put it on the README.
*

**Comment by tufranz** [comment]
* [x] add a example inventory file
* [x] rename this repo to `ansible-condor`.
* [ ] ~~find a way to specify the condor version. it can be the latest release~~
  condor is installed from os-version correlative repos: To change the installed condor version, the package-source needs to be changed.
* [x] this playbook should run for debian12 (bookworm)
* [x] find which ports are used to communicate with workers and submit and vice-versa. please document these.
* [x] Please document - the workflow as you described on the call - and put it on the README.
* [x] add to readme this part: This repo requires a file `jobservices.yml` - which has all the credentials in order that condor is able to communicate with discovery environment - the location of the file in **k8s-resources** repo is `k8s-resources/resources/configs/{{environment_name}}/jobservices.yml`
* [x]  (MOJIB) add a separate instruction on how to create an non-interactive app on DE - mention the workingdir - not to be used as `/tmp` and if its empty by default `road-runner` will assign this ```working_dir: /de-app-work``` as workingdir

**Comment by tufranz** [comment]
- [x] find which ports are used to communicate with workers and submit and vice-versa. please document these.  
All members should be reachable through `ssh`. It looks like there is no port needed to be reachable from outside. `submit-hosts` ans `worker-hosts` need the permission to send through `amqp` (default port: 5672) and the workers need additional permissions to reach the irods hosts (default port: 1247).
